### 🟡 Crear un nuevo personal administrativo
POST http://localhost:3000/administrative-staff
Content-Type: application/json
{
  "userId": 1, // Referencia al ID del usuario asociado
  "identification": "1092847563",// Número de identificación
  "phone": "3001234567",// Número de teléfono
  "startDate": "2025-10-18" //debe estar en formato YYYY-MM-DD
}
### 🟢 Obtener todo el personal administrativo
GET http://localhost:3000/administrative-staff  

### 🟢 Obtener un personal administrativo por ID
GET http://localhost:3000/administrative-staff/1

### 🔵 Actualizar un personal administrativo existente
PUT http://localhost:3000/administrative-staff/1
Content-Type: application/json

{
  "userId": 1, 
  "identification": "1092847563",
  "phone": "3001234567",
  "startDate": "2025-10-18"
}
### 🔴 Eliminar un personal administrativo existente
DELETE http://localhost:3000/administrative-staff/1

